[package]
name = "ragent"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "A framework for building LLM agents."

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
ragent_core = { path = "../ragent_core" }
ragent_derive = { path = "../ragent_derive" }
empathic_audio = { git = "https://github.com/empathic-ai/empathic-audio.git" }
common = { git = "https://github.com/empathic-ai/common.git" }
bevy = { version = "0.13.0", default-features = false, features = ["bevy_ui", "bevy_asset"] }
#bevy_reflect = { version = "0.11.0", default-features = false, features = ["bevy", "documentation"] }
time = { git = "https://github.com/empathic-ai/time.git", features = ["std", "wasm-bindgen", "alloc", "macros", "formatting", "parsing"] }
base64 = "0.21.5"
serde = { version = "1.0.149", features = ["derive"] }
serde_json = "1.0.89"
regex = "1.7.1"
fancy-regex = "0.11.0"
substring = "1.4.5"
async-channel = "1.8.0"
async-recursion = "1.0.2"
uuid = { version = "1.2.2", features = ["serde", "js", "wasm-bindgen", "v4"] }
gloo-console = "0.2.3"
gloo-utils = "0.1.6"
tokio = { version = "1.32.0", default-features = false, features = ["macros", "rt", "sync"] }
anyhow = "1.0.75"
bytes = "1.5.0"
futures = "0.3.25"
futures-util = "0.3.25"
futures-channel = "0.3.28"
nameof = "1.2.2"
documented = "0.1.2"
lazy_static = "1.4.0"
async-trait = "0.1.75"
crossbeam = "0.8.2"
cpal = "0.15.2"
aura-api-helper = { git = "https://github.com/empathic-ai/aura-api-helper.git" }
anthropic = { git = "https://github.com/Catchawink/anthropic-rs.git", default-features = false }
tokio-stream = "0.1.14"

[target.'cfg(not(target_arch = "xtensa"))'.dependencies]
reqwest = { version = "0.11.13", features = ["json", "stream"] }

[target.'cfg(all(not(target_arch = "xtensa"), not(target_arch = "wasm32")))'.dependencies]
#pyo3 = "0.20.0"
tonic = "0.10.2"
openai-api-rs = { git = "https://github.com/Catchawink/openai-api-rs.git", branch = "streaming" }

[target.'cfg(all(target_arch = "wasm32"))'.dependencies]
tonic = { version = "0.10.2", default-features = false, features = ["prost", "codegen"] }

[target.'cfg(all(not(target_arch = "wasm32")))'.dependencies]
deepgram = { git = "https://github.com/empathic-ai/deepgram-rust-sdk.git" }
openai-api-rs = { git = "https://github.com/Catchawink/openai-api-rs.git", branch = "streaming" }

[build-dependencies]
tonic-build = { version = "0.10.2", default-features = false, features = ["prost"] }
